controllers/ContactsController.php
<?php

namespace app\controllers;

use app\models\Organization;
use Yii;
use yii\helpers\ArrayHelper;
use domain\entities\Contact\Contact;
use domain\entities\Contact\ContactSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use domain\services\ContactService;
use domain\services\FilterService;
use domain\forms\Contact\ContactForm;

/**
 * ContactsController implements the CRUD actions for Contact model.
 */
class ContactsController extends Controller
{
	
	private $contactService;
	private $organization;

	public function __construct($id, $module, ContactService $contactService, Organization $organization, $config = array()) {
		parent::__construct($id, $module, $config);
		$this->contactService = $contactService;
		$this->organization = $organization;

	}
	
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Contact models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ContactSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contact model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
		$form = $this->contactService->findById($id);
        return $this->render('view', [
            'model' => $form,
        ]);
    }

    /**
     * Creates a new Contact model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new ContactForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			try {
				$id = $this->contactService->create($form);
				return $this->redirect(['view', 'id' => $id]);
			} catch (\Exception $e) {
				Yii::$app->session->setFlash('domainError', $e);
			}
        }
        $array = Organization::find()->all();
        $organizations = ArrayHelper::map($array, 'id', 'mainaddress_adressname');
        return $this->render('create', [
            'model' => $form,
            'organizations' => $organizations,
        ]);
    }

    /**
     * Updates an existing Contact model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $form = $this->contactService->findById($id);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			try {
				$this->contactService->edit($form);
				return $this->redirect(['organization/view', 'id' => $form->organization_id]);
			} catch (\Exception $e) {
				Yii::$app->session->setFlash('domainError', $e);
			}
        }
        $organizations = $this->contactService->getallorg();
        $currentorg = $this->contactService->getcurrentorg($form->organization_id);
        return $this->render('update', [
            'model' => $form,
            'currentorg' => $currentorg,
            'organizations' => $organizations,
        ]);
    }

    /**
     * Deletes an existing Contact model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {    if (Yii::$app->user->can('admin')) {
		$this->contactService->deleteById($id); }
		else Yii::$app->session->setFlash('error', 'У вас недостаточно прав для данной операции');
        return $this->redirect(['index']);
    }

    public function beforeAction($action) {

        if (Yii::$app->user->isGuest)
            $this->redirect('../site/login');

        return parent::beforeAction($action);
    }
}

controllers/FiltersController.php
<?php

namespace app\controllers;

use Yii;
use domain\entities\Filter\Filter;
use domain\entities\Filter\FilterSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use domain\services\FilterService;
use domain\forms\FilterForm;
use domain\exceptions\CantSaveException;

/**
 * FiltersController implements the CRUD actions for Filter model.
 */
class FiltersController extends Controller
{
	
	/**
	 *
	 * @var FilterService 
	 */
	private $filterService;
	
	/**
	 * 
	 * @param FilterService $service
	 * @param type $id
	 * @param type $module
	 * @param type $config
	 */
	public function __construct($id, $module, FilterService $service, $config = array()) {
		parent::__construct($id, $module, $config);
		$this->filterService = $service;
	}
	
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Filter models.
     * @return mixed
     */
    public function actionIndex()
    {	
        $searchModel = new FilterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Filter model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
		$form = $this->filterService->findById($id);
        return $this->render('view', [
            'model' => $form,
        ]);
    }

    /**
     * Creates a new Filter model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new FilterForm();

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			try {
				$id = $this->filterService->create($form);
				return $this->redirect(['view', 'id' => $id]);
			} catch (CantSaveException $exception) {
				Yii::$app->session->setFlash('domainError', $exception);
			}
        }

        return $this->render('create', [
            'model' => $form,
        ]);
    }

    /**
     * Updates an existing Filter model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $form = $this->filterService->findById($id);
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
				$id = $this->filterService->edit($form);
				return $this->redirect(['view', 'id' => $id]);
			} catch (CantSaveException $exception) {
				Yii::$app->session->setFlash('domainError', $exception);
			}
        }

        return $this->render('update', [
            'model' => $form,
        ]);
    }

    /**
     * Deletes an existing Filter model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->filterService->deleteById($id);
        return $this->redirect(['index']);
    }


    public function beforeAction($action) {

        if (Yii::$app->user->isGuest)
            $this->redirect('../site/login');

        return parent::beforeAction($action);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            /* 'access' => [
                 'class' => AccessControl::className(),
                 'only' => ['logout'],
                 'rules' => [
                     [
                         'actions' => ['logout'],
                         'allow' => true,
                         'roles' => ['@'],
                     ],
                 ],
             ], */
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionLanguage($language)
    {
        $cookies = Yii::$app->response->cookies;
        $cookies->remove('language');
        if ($language == "en") {
            $cookies->add(new \yii\web\Cookie([
                'name' => 'language',
                'value' => 'en-EN',
            ]));
            // return $this->refresh();
        } else if ($language == "ru") {
            $cookies->add(new \yii\web\Cookie([
                'name' => 'language',
                'value' => 'ru-RU',
            ]));
            // return $this->refresh();
        }
        return $this->redirect('index');
    }

    public function actionIndex()
    {

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */


    public function actionAbout()
    {

        return $this->render('about');
    }




}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSerach;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
			'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['admin'],
                ],
            ],
        ]
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSerach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->redirect('index');
    }


    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('index');
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/_sidebar.php
<<?php

use yii\bootstrap\Modal;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;

?>

<header id="topnav">
    <div class="topbar-main">
        <div class="container">

            <!-- Logo container-->
            <div class="logo">
                <a href="<?=\yii\helpers\Url::home()?>" class="logo"><span>Kron<i
                                class="md md-album"></i>CRM</span></a>
            </div>
            <!-- End Logo container-->


            <div class="menu-extras">


                <ul class="nav navbar-nav navbar-right pull-right">

                    <li class="dropdown navbar-c-items">
                        <a href="" class="dropdown-toggle waves-effect waves-light profile" data-toggle="dropdown"
                           aria-expanded="true">
                            <?php
                            echo Yii::$app->user->isGuest ? ('<a href="'.\yii\helpers\Url::to(['site/login']).'">'.Yii::t('app', 'Login').'</a>') : (Yii::$app->user->identity->username)
                            ?>


                        </a>
                        <ul class="dropdown-menu">
                            <?php if (!Yii::$app->user->isGuest) {
                                echo  '<li><a href="#">' .Html::beginForm(['/site/logout'], 'post') .'&nbsp;&nbsp;&nbsp;&nbsp;' .Html::submitButton(
                                        Yii::t('app', 'Logout'),
                                        ['class' => 'btn btn-link',
                                        ]
                                    )
                                   .Html::endForm()   . '</a></li>';


                            } ?>

                        </ul>
                    </li>
                </ul>
                <div class="menu-item">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </div>
            </div>

        </div>
    </div>

    <div class="navbar-custom">

            <div id="navigation">

<?php if (!Yii::$app->user->isGuest) {
                    NavBar::begin([
                        'options' => [
                            'class' => 'navigation-menu',

                        ],
                    ]);

                    echo   Nav::widget([
                        'options' => ['class' => 'navigation-menu'],
                        'items' => [
                            Yii::$app->user->can('admin') ?
                                ['label' => Yii::t('app', 'Users'), 'url' => ['/users/index'], 'options' => ['class' => 'has-submenu']]: '',
                           // ['label' => Yii::t('app', 'Index'), 'url' => ['/site/index'], 'options' => ['class' => 'has-submenu']],
                            ['label' => Yii::t('app', 'Filters'), 'url' => ['/filters/index'], 'options' => ['class' => 'has-submenu']],
                            ['label' => Yii::t('app', 'Contacts'), 'url' => ['/organization/index'], 'options' => ['class' => 'has-submenu']],

                            ['label' => Yii::t('app', 'Templates'), 'url' => ['/template/index'], 'options' => ['class' => 'has-submenu']],
                            ['label' => Yii::t('app', 'Notifications'), 'url' => ['/notifications/index'], 'options' => ['class' => 'has-submenu']],
                        ],
                    ]);
                    NavBar::end(); }
                else echo '<ul class="navigation-menu"><br><br><br></ul>';

                    ?>


        </div> <!-- end container -->
    </div> <!-- end navbar-custom -->
</header>

views/layouts/basic.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this); ?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript">document.cookie = "language=ru-RU; path=/; expires=" + date.toUTCString();</script>
        <link rel="shortcut icon" href="images/favicon_1.ico">

         <?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>

    </head>
    <body>
<?php $this->beginBody() ?>

        <?=$this->render('_sidebar');?>


        <div class="wrapper">
            <div class="container">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
                <?= Alert::widget() ?>
      <?=$content;?>


                <?php
                $language = Yii::$app->request->cookies['language'];

                if ($language == "en-EN") {
                $url = "ru";
                $label = "RU";
                }
                else if ($language == "ru-RU") {
                    $url = "en";
                    $label = "EN";
                }
                else {
                    $url = "ru";
                    $label = "RU";
                }
                ?>

                <!-- Footer -->
                <footer class="footer text-right">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-6">
                                Футер
                            </div>
                            <div class="col-xs-6">
                                <ul class="pull-right list-inline m-b-0">
                                    <li>

                                        <a href=<?=\yii\helpers\Url::to(['site/language', 'language' => $url])?>><?=$label?></a>

                                    </li>
                                    <li>

                                    </li>
                                    <li>

                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- End Footer -->

            </div>
        </div>

<?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);


  if (!Yii::$app->user->isGuest) {
    echo   Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            Yii::$app->user->can('admin') ?
            ['label' => 'Пользователи', 'url' => ['/users/index']]: '',
            ['label' => 'Главная', 'url' => ['/site/index']],
            ['label' => 'Фильтры', 'url' => ['/filters/index']],
            ['label' => 'Организации', 'url' => ['/organization/index']],
            ['label' => 'Контакты', 'url' => ['/contacts/index']],
            ['label' => 'Шаблоны', 'url' => ['/template/index']],
            ['label' => 'Рассылки', 'url' => ['/notifications/index']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Авторизация', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )

        ],
    ]);
    NavBar::end(); }
    else {
     echo   Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [

            Yii::$app->user->isGuest ? (
                ['label' => 'Авторизация', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end(); }
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>