controllers/NotificationsController.php
<?php

namespace app\controllers;

use app\models\TemplatesModel\TemplatesModel;
use domain\entities\Contact\Contact;
use Yii;
use domain\entities\Notification\NotificationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use domain\services\NotificationService;
use domain\services\FilterService;
use domain\forms\Notification\NotificationForm;
use domain\services\NotificationDispatcher;
use app\models\User;
use domain\entities\Notification\NotificationFilter;
use app\models\OrganizationFilter;


/**
 * NotificationsController implements the CRUD actions for Notification model.
 */
class NotificationsController extends Controller
{

    protected $notificationService;
    protected $filterService;
    protected $notificationDispatcher;
    protected $templatesModel;

    public function __construct(
        $id,
        $module,
        NotificationService $notificationService,
        TemplatesModel $templatesModel,
        FilterService $filterService,
        NotificationDispatcher $notificationDispatcher,
        $config = array()
    )
    {
        parent::__construct($id, $module, $config);
        $this->notificationService = $notificationService;
        $this->filterService = $filterService;
        $this->notificationDispatcher = $notificationDispatcher;
        $this->templatesModel = $templatesModel;

    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Notification models.
     * @return mixed
     */
    public function actionIndex()
    {


        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Notification model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $form = $this->notificationService->findById($id);
        return $this->render('view', [
            'model' => $form,
        ]);
    }

    /**
     * Creates a new Notification model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $form = new NotificationForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            if (Yii::$app->request->isPjax) {
                try {
                    $id = $this->notificationService->create($form);
                    Yii::$app->session->setFlash('success', 'Рассылка сохранена');
                    $form->id = $id;
//	return $this->redirect(['view', 'id' => $id]);
                } catch (\Exception $e) {
                    Yii::$app->session->setFlash('domainError', $e);
                }
            }
        }
        $filters = ArrayHelper::map($this->filterService->all(), 'id', 'title');
        $templates = $this->templatesModel->findtemplates('notification');
        return $this->render('create', [
            'templates' => $templates,
            'model' => $form,
            'filters' => $filters,

        ]);
    }

    /**
     * Updates an existing Notification model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $form = $this->notificationService->findById($id);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
            try {
                $id = $this->notificationService->edit($form);
                return $this->redirect(['view', 'id' => $id]);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('domainError', $e);
            }
        }

        $filters = ArrayHelper::map($this->filterService->all(), 'id', 'title');
        $templates = $this->templatesModel->findtemplates('notification');
        $currenttemplate = $this->templatesModel->findcurrenttemp($id);
        return $this->render('update', [
            'model' => $form,
            'filters' => $filters,
            'templates' => $templates,
            'currenttemplate' => $currenttemplate,
        ]);
    }

    /**
     * Deletes an existing Notification model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return \redirect to index
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->notificationService->deleteById($id);

        return $this->redirect(['index']);
    }

    /**
     * @param integer $id
     */
    public function actionSend($id)
    {
        try {
            $this->notificationDispatcher->notifyById($id);
            Yii::$app->session->setFlash('successNotification', true);
        } catch (\Exception $e) {
            Yii::$app->session->setFlash('domainError', $e);
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     */
    public function actionSendone($id) {
        $form = new NotificationForm();
        if ($form->load(Yii::$app->request->post())) {
            if ($form->contact !== "") {
                $this->notificationDispatcher->notifyByContactId($form->contact, $id);
                Yii::$app->session->setFlash('success', 'Рассылка успешно отправлена');
            }
        }
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionTemp($id)
    {   $filters = ArrayHelper::map($this->filterService->all(), 'id', 'title');
        $a = NotificationFilter::find()->where(['notification_id' => $id])->all();
        $b = ArrayHelper::getColumn($a,'filter_id');
        $c = OrganizationFilter::find()->where(['filter_id' => $b])->all();
        $e = ArrayHelper::getColumn($c,'organization_id');
        $r = Contact::find()->where(['organization_id' => $e])->all();
        $count = count($r);
        $array = Contact::find()->all();
        $users = ArrayHelper::map($array, 'email', 'client_name');
        $session = Yii::$app->session;
        $session->open();
        $form = $this->notificationService->findById($id);
        if ($form->load(Yii::$app->request->post())) {
            if ($form->test !== "") {
                $this->notificationDispatcher->notifyTest($form->test, $id);
                Yii::$app->session->setFlash('success', 'Тестовая рассылка успешно отправлена');
            }
        }
        $items = TemplatesModel::findonetemp($form->id_template);
        $template = implode($items);
        $session['template'] = $template;
        $model = User::find()->where(['username' => Yii::$app->user->identity->username])->one();
        return $this->render('template', [
            'model' => $form,
            'users' => $users,
            'template' => $template,
            'test' => $model->email,
            'count' => $count,
            'filters' => $filters]);
    }


}

views/notifications/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
//use yii\bootstrap\Alert;
use kartik\select2\Select2;
use yii\widgets\Pjax;
use app\widgets\Alert;


/* @var $this yii\web\View */
/* @var $model \domain\entities\Notification\NotificationForm */
/* @var $form yii\widgets\ActiveForm */
/* @var $items \app\models\TemplatesModel\TemplatesModel */

?>

<?php if ($currenttemplate) {
    $script = <<< JS
     val = "$currenttemplate";
     text = '$model->content';
     document.getElementById('preview').src="../template/frame?template="+val;
      var iframe = document.getElementById('preview');
     
      function func() {
      iframe.contentWindow.document.getElementById('content').innerHTML = text;
      } 
     setTimeout(func, 1000); 
 
             
    
    
     //document.getElementById('html-1').setAttribute('aria-pressed', 'true');
JS;
    $this->registerJS($script, yii\web\View::POS_LOAD);
} ?>


<script type="text/javascript">
    midVal = "";
    prevVal = "";
    postval = "";
    var count = 0;


    setInterval(function () {
        var curVal = $("#contentt").val();
        if (prevVal !== curVal) {
            prevVal = curVal;
            var iframe = document.getElementById('preview');
            if (prevVal) {
                iframe.contentWindow.document.getElementById('content').innerHTML = prevVal;
            }
        }
    }, 100);

    function iframeLoaded() {
        var iFrameID = document.getElementById('preview');
        if (iFrameID) {
            iFrameID.height = 900 + "px";
            iFrameID.style = "width: 800px;display: block; position: relative; top: -100px; transform: scale(0.9); width: 100%; border: none;";
        }
    }

    function getval() {
        vall = $("#notificationform-id_template option:selected").val();
        maketemplate(vall);
    }

    function maketemplate(val) {
        if (val != "undefined") {
            if (val !== "") {
                postval = val;
                document.getElementById('preview').src = "../template/frame?template=" + val;
                document.getElementById('preview').hidden = false;
            }
        }

    }
</script>





<div class="col-md-6">
    <?php Pjax::begin() ?>
    <?=Alert::widget()?>
    <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]); ?>

     <?= $form->field($model, 'filters')->widget(Select2::class, [
        'options' =>
            [
                'placeholder' => 'Выберите один или несколько фильтров',
                'multiple' => true
            ],
        'data' => $filters,
        'pluginOptions' =>
            [
                'allowClear' => true,
            ]
    ]) ?>

    <?= $form->field($model, 'title')->textInput(); ?>

    <?= $form->field($model, 'heading')->textInput(); ?>

    <?php
    $params = [
        'prompt' => 'Выбор шаблона',
        'onchange' => 'getval();',
        'options' =>
            [
                $currenttemplate => ['Selected' => true],
            ]
    ];
    ?>



    <?= $form->field($model, 'id_template')->dropDownList($templates, $params); ?>

    <?= \froala\froalaeditor\FroalaEditorWidget::widget([
        'model' => $model,
        'attribute' => 'content',
        'options' =>
            [
                // html attributes
                'id' => 'contentt',
            ],
        'clientOptions' =>
            [
                'toolbarInline' => false,
                'height' => 200,
                'theme' => 'royal',//optional: dark, red, gray, royal
                'language' => 'en_gb',
                'placeholderText' => 'Контент сообщения',
                'toolbarButtons' => ['html', 'bold', 'italic', '|', 'insertImage'],
                'imageUploadParam' => 'file',
                'imageUploadURL' => \yii\helpers\Url::to(['template/upload/'])
            ],
        'clientPlugins' => ['code_view', 'image']
    ]); ?>

    <?= $form->field($model, 'email')->checkbox() ?>

    <?= $form->field($model, 'sms')->checkbox() ?>




        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success', 'id' => 'subbut']) ?>

        <?php if ($model->id>0) echo Html::a(Yii::t('app', 'Send'), ['notifications/temp', 'id' => $model->id], ['class' => 'btn btn-success']) ?>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end() ?>
</div>

<div class="col-md-6">
    <iframe id="preview" onload="iframeLoaded()" name="preview" src="" hidden></iframe>
</div>

views/notifications/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model domain\entities\Notification\NotificationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="notification-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'heading') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'sms') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/notifications/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model domain\entities\Notification\Notification */
/* @var $filters \domain\forms\FilterForm */

$this->title = Yii::t('app', 'Create notification');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Notifications'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-create">


    <h1><?= Html::encode($this->title) ?></h1>

    

    <?= $this->render('_form', [
        'model' => $model,
		'filters' => $filters,
        'templates' => $templates,
        'currenttemplate' => null,
    ]) ?>

</div>

views/notifications/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use domain\widgets\NotificationAlert;

/* @var $this yii\web\View */
/* @var $searchModel domain\entities\Notification\NotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Notifications');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="notification-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create notification'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
	
	<?= NotificationAlert::widget(); ?>
    <div class="card-box">
        <div class="table-responsive">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
                       'tableOptions' => [
        'class' => 'table table-hover mails m-0 table table-actions-bar', ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn',
			],
			'title',
            'heading',
           [
			 'attribute' => 'content',
			 'format' => 'raw',
           ],
			'email:boolean',
            'sms:boolean',
			'template.t_description:ntext',
			[
				'format' => 'raw',
				'value' => function($model) {
			return Html::a(Yii::t('app', 'Send'), ['notifications/temp', 'id' => $model->id], ['class' => 'btn btn-info']);
				}
			],
            ['class' => 'yii\grid\ActionColumn',
            'header' => Yii::t('app', 'Actions'),
            'template' => '{update} {delete}'],
        ],
    ]); ?>
        </div>
    </div>

</div>

views/notifications/template.php
<?php



use yii\helpers\Html;
use yii\widgets\ActiveForm;
use domain\widgets\NotificationAlert;
use yii\helpers\Url;
use yii\bootstrap\Tabs;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model domain\entities\Notification\NotificationForm */
/* @var $form ActiveForm */

$this->params['breadcrumbs'][] = [
   // 'template' => "<li><b>{link}</b></li>\n", //  шаблон для этой ссылки
    'label' => Yii::t('app', 'Notifications'), // название ссылки
    'url' => ['/notifications'] // сама ссылка
];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Dispatch')];
?>

<?php
$content = $model->content;
$script = <<< JS
var content = '$content';
JS;

$this->registerJs($script, yii\web\View::POS_END); ?>


<script type="text/javascript">


    window.onload = function() {
            var iFrameID = document.getElementById('preview');
            iFrameID.height = iFrameID.contentWindow.document.body.scrollHeight + 'px';
            iFrameID.contentWindow.document.getElementById('content').innerHTML = content;

        }

</script>

<?php $form = ActiveForm::begin(); ?>
<div>
    <?= NotificationAlert::widget(); ?>
    <iframe id="preview" style="display: block; border: 1px solid #ccc; width: 65%; margin: auto; " src="<?= Url::to(['template/frame?template='])?><?=$template?>"></iframe>
    <br>

    <?php $test = $form->field($model, 'test')->textinput(['value' => $test]) ?>
    <br><?php $test .= Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-info', 'formaction' => 'temp?id='.$model->id]) ?>

         <?php $tab = 'Количество получателей: ' .$count .' <br><br>'; $tab .= Html::a(Yii::t('app', 'Send all'), ['notifications/send', 'id' => $model->id],['data' => ['confirm' => 'Отправить рассылку '.$count.' контакту(ам)?'], 'class' => 'btn btn-success']);?>

    <?=Html::a(Yii::t('app', 'Edit'), ['notifications/update', 'id' => $model->id], ['class' => 'btn btn-primary']);?>
  <br><br>
        </div>
<?php $one =  $form->field($model, 'contact')->widget(Select2::classname(), [
    'data' => $users,
    'language' => 'ru',
    'options' => ['placeholder' => 'Выберите получателя'],
    'pluginOptions' => [
        'allowClear' => true
    ],
]);

$one .=   Html::submitButton(Yii::t('app', 'Send'), ['class' => 'btn btn-info', 'formaction' => 'sendone?id='.$model->id]); ?>

<?= Tabs::widget([
    'items' => [
        [
            'label' => Yii::t('app', 'Send for test'),
            'content' => $test,
        ],
        [
            'label' => Yii::t('app', 'Send to all segments'),
            'content' => $tab,
           // 'active' => true // указывает на активность вкладки
        ],
        [
            'label' => Yii::t('app', 'Send to one contact'),
            'content' => $one,
        ],


    ]
]); ?>


<?php ActiveForm::end(); ?>

</div>

views/notifications/update.php
<?php

use yii\helpers\Html;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model domain\entities\Notification\Notification */

$this->title = Yii::t('app', 'Update notification') . ' '. $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Notifications'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="notification-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
		'filters' => $filters,
        'templates' => $templates,
        'currenttemplate' => $currenttemplate,
    ]) ?>

</div>

views/notifications/view.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model domain\entities\Notification\Notification */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Notifications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'heading',
            'content:html',
            'email:email',
            'sms',
            'id_template',
			[
				'attribute' => 'filters',
				'format' => 'raw',
				'value' => function($model) {
					$filters = $model->getFilterModels();
					return implode(', ', ArrayHelper::getColumn($filters, 'title'));
				}
			]
        ],
    ]) ?>

    <?= Html::a('Перейти к отправке', ['notifications/temp', 'id' => $model->id], ['class' => 'btn btn-success']) ?>

</div>