controllers/ContactsController.php
<?php

namespace app\controllers;

use app\models\Organization;
use Yii;
use yii\helpers\ArrayHelper;
use domain\entities\Contact\Contact;
use domain\entities\Contact\ContactSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use domain\services\ContactService;
use domain\services\FilterService;
use domain\forms\Contact\ContactForm;

/**
 * ContactsController implements the CRUD actions for Contact model.
 */
class ContactsController extends Controller
{
	
	private $contactService;
	private $organization;

	public function __construct($id, $module, ContactService $contactService, Organization $organization, $config = array()) {
		parent::__construct($id, $module, $config);
		$this->contactService = $contactService;
		$this->organization = $organization;

	}
	
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Contact models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ContactSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contact model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
		$form = $this->contactService->findById($id);
        return $this->render('view', [
            'model' => $form,
        ]);
    }

    /**
     * Creates a new Contact model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $form = new ContactForm();
        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			try {
				$id = $this->contactService->create($form);
				return $this->redirect(['view', 'id' => $id]);
			} catch (\Exception $e) {
				Yii::$app->session->setFlash('domainError', $e);
			}
        }
        $array = Organization::find()->all();
        $organizations = ArrayHelper::map($array, 'id', 'mainaddress_adressname');
        return $this->render('create', [
            'model' => $form,
            'organizations' => $organizations,
        ]);
    }

    /**
     * Updates an existing Contact model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $form = $this->contactService->findById($id);

        if ($form->load(Yii::$app->request->post()) && $form->validate()) {
			try {
				$this->contactService->edit($form);
				return $this->redirect(['organization/view', 'id' => $form->organization_id]);
			} catch (\Exception $e) {
				Yii::$app->session->setFlash('domainError', $e);
			}
        }
        $organizations = $this->contactService->getallorg();
        $currentorg = $this->contactService->getcurrentorg($form->organization_id);
        return $this->render('update', [
            'model' => $form,
            'currentorg' => $currentorg,
            'organizations' => $organizations,
        ]);
    }

    /**
     * Deletes an existing Contact model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {    if (Yii::$app->user->can('admin')) {
		$this->contactService->deleteById($id); }
		else Yii::$app->session->setFlash('error', 'У вас недостаточно прав для данной операции');
        return $this->redirect(['index']);
    }

    public function beforeAction($action) {

        if (Yii::$app->user->isGuest)
            $this->redirect('../site/login');

        return parent::beforeAction($action);
    }
}

controllers/OrganizationController.php
<?php

namespace app\controllers;

use app\models\ContactForm;
use app\models\OrganizationFilter;
use app\models\OrganizationNotes;
use app\models\OrganizationNotesSearch;
use app\models\User;
use domain\entities\Contact\Contact;
use domain\entities\Contact\ContactSearch;
use domain\entities\Filter\Filter;
use domain\exceptions\CantSaveException;
use Yii;
use app\models\Organization;
use app\models\OrganizationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadForm;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use domain\services;

/**
 * OrganizationController implements the CRUD actions for Organization model.
 */
class OrganizationController extends Controller
{
    public $repository;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        //Yii::$app->language = 'en-EN';
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Organization models.
     * @return mixed
     */


    public function actionIndex()
    {

        $searchModel = new OrganizationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Organization model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {   $model1 = new OrganizationNotes(['organization_id' => $id, 'user_id' => Yii::$app->user->id]);
        $searchModel = new OrganizationNotesSearch(['organization_id' => $id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];
        $dataProvider->pagination->pageSizeLimit = ['1', '10'];

        $searchModel1 = new ContactSearch(['organization_id' => $id]);
        $dataProvider1 = $searchModel1->search(Yii::$app->request->queryParams);

        $query = OrganizationFilter::find()->select('filter_id')->where(['organization_id' => $id])->all();
        $query = ArrayHelper::getColumn($query, 'filter_id');
        $filters = [];
        foreach ($query as $key => $filter) {
           $q =  ArrayHelper::getColumn(Filter::find()->where(['id' => $filter])->all(), 'description');
           array_push($filters, implode($q));
        }
      //  $client_name = null;
        $contacts = new Contact('','',$id,'', '', '', '');
        if ($contacts->load(Yii::$app->request->post()) && $contacts->save()) {
          //  $contacts = new Contact('', '', $id);
            Yii::$app->session->setFlash('success', "Контакт сохранен");
            if (!Yii::$app->request->isPjax) {
                return $this->redirect(['organization/view'], ['id' => $id]);

            }
        }

        if ($model1->load(Yii::$app->request->post()) && $model1->save()) {
            $model1->note = "";
            Yii::$app->session->setFlash('success', "Заметка сохранена");
            if (!Yii::$app->request->isPjax) {
               return $this->redirect(['organization/view'], ['id' => $id]);
            }
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
            'model1' => $model1,
            'contacts' => $contacts,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'searchModel1' => $searchModel1,
            'dataProvider1' => $dataProvider1,
            'filters' => $filters,
        ]);

    }

    /**
     * Creates a new Organization model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Organization();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $filters = ArrayHelper::map(Filter::find()->all(), 'id', 'title');
        return $this->render('create', [
            'model' => $model,
            'filters' => $filters,
        ]);
    }

    /**
     * Updates an existing Organization model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
       /* $note = new OrganizationNotes;
        $note->organization_id = $id;
        $note->user_id = Yii::$app->user->id; */
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $filters = ArrayHelper::map(Filter::find()->all(), 'id', 'title');
        return $this->render('update', [
            'model' => $model,
            'filters' => $filters,
        //    'note' => $note,
        ]);
    }

    /**
     * Deletes an existing Organization model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {

        if (Yii::$app->user->can('admin')) {
            try {
                $this->findModel($id)->delete();
            } catch (\Exception $exception) {
                Yii::$app->session->setFlash('error', 'У организации есть контакты или заметки. Удалить невозможно');
            }
        }
        else Yii::$app->session->setFlash('error', 'У вас недостаточно прав для данной операции');
        return $this->redirect(['index']);
    }

    /**
     * Finds the Organization model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Organization the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Organization::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @return string|\yii\web\Response
     * @throws \PHPExcel_Reader_Exception
     */
    public function actionExcel()
    {
        if (Yii::$app->user->can('admin')) {
            $model = new Organization();
           // $contact = new Contact('', '', '', '', '', '');
            if (Yii::$app->request->isPost) {
                $model->excelfile = UploadedFile::getInstance($model, 'excelfile');
                if ($model->upload()) {
                    $sure = false;
                    $count = 0;
                    $unic = 0;
                    $input = array_keys($model->attributes);
                    array_shift($input);
                    array_pop($input);
                    $base_path = Yii::getAlias('@app');
                    $excel = \PHPExcel_IOFactory::load($base_path . '/excelupload/' . $model->excelfile->name);
                    foreach ($excel->getWorksheetIterator() as $worksheet) {
                        $lists[] = $worksheet->toArray();
                    }
                    foreach ($lists as $list) {
                        foreach ($list as $row) {
                            if ($sure == false) {
                                $sure = true;
                            } else {
                                if (count($row) > 20) {
                                    array_pop($row);
                                    $masiv = array_combine($input, $row);
                                    $model->attributes = $masiv;

                                    try {

                                        $model->save(false);
                                        $unic++;
                                        $contact = new Contact('', $model->agent_name, $model->id, '', '', '', 'agent');
                                        $contact->save(false);
                                        $contact = new Contact('', $model->clerk_name, $model->id, '', '', '', 'clerk');
                                        $contact->save(false);
                                    } catch (\Exception $e) {
                                    }
                                    $model->id = FALSE;
                                    $model->isNewRecord = TRUE;
                                    $count++;
                                }
                            }
                            foreach ($row as $col) {
                            }
                        }
                    }
                    Yii::$app->session->setFlash('success', $count . ' организаций было обнаружено. Из них ' . $unic . ' уникальная(ых) запись(ей) было добавлено.');
                    return $this->redirect('index');
                }
            }
        }
        else {Yii::$app->session->setFlash('error', 'У вас недостаточно прав для данной операции');  return $this->redirect(Yii::$app->request->referrer);}
        return $this->render('excel', ['model' => $model]);
    }

}

controllers/OrganizationNotesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrganizationNotes;
use app\models\OrganizationNotesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrganizationNotesController implements the CRUD actions for OrganizationNotes model.
 */
class OrganizationNotesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrganizationNotes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrganizationNotesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrganizationNotes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OrganizationNotes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrganizationNotes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing OrganizationNotes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing OrganizationNotes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * Finds the OrganizationNotes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrganizationNotes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrganizationNotes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/organization/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\widgets\Pjax;


/* @var $this yii\web\View */
/* @var $model app\models\Organization */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="organization-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class='col-sm-6 col-md-6' id='id'>
        <?= $form->field($model, 'filters')->widget(Select2::class, [
            'options' => [
                'placeholder' => Yii::t('app', 'Select one or more filters'),
                'multiple' => true
            ],
            'data' => $filters,
            'pluginOptions' => [
                'allowClear' => true,
            ]
        ]) ?>

        <?= $form->field($model, 'mainaddress_adressname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Match_Code')->textInput(['maxlength' => true]) ?>



    <?= $form->field($model, 'country')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'zipcode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'clerk_staffId')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'clerk_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'associationnumber')->textInput() ?>

    <?= $form->field($model, 'mainassociationnumber')->textInput() ?>

    <?= $form->field($model, 'agent_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'isoCode')->textInput(['maxlength' => true]) ?>

    <?=$form->field($model, 'top_customer')->dropDownList([
    '' => '',
    '0' => 'Да',
    '1' => 'Нет'
    ]); ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>
    </div>
    <div class='col-sm-6 col-md-6' id='id2'>
    <?= $form->field($model, 'Accounting_clerk_staffId')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Accounting_clerk_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Common_Match_Code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mainaddress_addressname2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_addressname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_city')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_fax')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_mobilephone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'deliveryaddress_email')->textInput(['maxlength' => true]) ?>



    </div>


    <?php ActiveForm::end(); ?>



</div>

views/organization/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrganizationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="organization-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'Match_Code') ?>

    <?= $form->field($model, 'mainaddress_adressname') ?>

    <?= $form->field($model, 'country') ?>

    <?= $form->field($model, 'zipcode') ?>

    <?php // echo $form->field($model, 'city') ?>

    <?php // echo $form->field($model, 'clerk_staffId') ?>

    <?php // echo $form->field($model, 'clerk_name') ?>

    <?php // echo $form->field($model, 'associationnumber') ?>

    <?php // echo $form->field($model, 'mainassociationnumber') ?>

    <?php // echo $form->field($model, 'agent_name') ?>

    <?php // echo $form->field($model, 'isoCode') ?>

    <?php // echo $form->field($model, 'top_customer') ?>

    <?php // echo $form->field($model, 'Accounting_clerk_staffId') ?>

    <?php // echo $form->field($model, 'Accounting_clerk_name') ?>

    <?php // echo $form->field($model, 'Common_Match_Code') ?>

    <?php // echo $form->field($model, 'mainaddress_addressname2') ?>

    <?php // echo $form->field($model, 'deliveryaddress_addressname') ?>

    <?php // echo $form->field($model, 'deliveryaddress_city') ?>

    <?php // echo $form->field($model, 'deliveryaddress_phone') ?>

    <?php // echo $form->field($model, 'deliveryaddress_fax') ?>

    <?php // echo $form->field($model, 'deliveryaddress_mobilephone') ?>

    <?php // echo $form->field($model, 'deliveryaddress_email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/organization/create.php
<?php

use yii\helpers\Html;


/**
 * @var $this yii\web\View
 * @var $model app\models\Organization
 * @var $filters \domain\entities\Filter\Filter
 */

$this->title = Yii::t('app', 'Create organization');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Organizations'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="organization-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'filters' => $filters,
    ]) ?>

</div>

views/organization/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use app\widgets\Alert;
use yii\helpers\Url;
use yii\widgets\ListView;
use kartik\select2\Select2;
/* @var $this yii\web\View */
/* @var $model app\models\Organization */

$this->title = $model->mainaddress_adressname;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Contacts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<style>.select2-container--krajee.select2-container--disabled .select2-selection, .select2-container--krajee.select2-container--disabled .select2-selection--multiple .select2-selection__choice {background-color:white;}
    .select2-container--krajee.select2-container--disabled .select2-search__field, .select2-container--krajee.select2-container--disabled .select2-selection {cursor: pointer;}
</style>

<div class="organization-view">
    <?php
    $this->registerJs(
        '$("document").ready(function(){
            $("#new_note").on("pjax:end", function() {
            $.pjax.reload({container:"#notes"});  //Reload GridView
        });
    });'
    );
    ?>
    <?php $this->registerJs("
    $('#users tbody td').css('cursor', 'pointer');
    $('#users tbody td').on('click', function (e) {
        var id = $(this).closest('tr').data('key');
        if(e.target == this)
        location.href = '" . Url::to(['contacts/update']) . "?id=' + id;
        });
        ", yii\web\View::POS_END);


    ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <div class="col-md-5 left-side-home-outer" style="padding-left: 0px;">
        <div class="card-box">
            <div class="table-responsive">
<?= Html::label(Yii::t('app', 'Directions')) ?>
            <?=Select2::widget([
    'name' => 'state_2',
   'readonly' => true,
    'hideSearch' => true,
    'showToggleAll' => false,
   'disabled' => true,
    'value' => $filters,
    //'theme' => 'classic',
    'options' => ['multiple' => true, 'placeholder' => Yii::t('app', 'Empty')],

]); ?>



    <?= DetailView::widget([
        'model' => $model,

        'attributes' => [
                'mainaddress_adressname',
        //    'id',
            'Match_Code',
          /* [
                'label' => 'Направления',
                'value' => $filters,
            ], */
                'country',
            'zipcode',
            'city',
            'clerk_staffId',
            'clerk_name',
            'associationnumber',
            'mainassociationnumber',
            'agent_name',
            'isoCode',
            'top_customer',
            'Accounting_clerk_staffId',
            'Accounting_clerk_name',
            'Common_Match_Code',
            'mainaddress_addressname2',
            'deliveryaddress_addressname',
            'deliveryaddress_city',
            'deliveryaddress_phone',
            'deliveryaddress_fax',
            'deliveryaddress_mobilephone',
            'deliveryaddress_email:email',
        ],
    ]) ?>
            </div></div></div>
    <div class="col-md-7 left-right-home-outer">
         <?php Pjax::begin(['enablePushState' => false,'timeout' => 5000,'id' => 'my_pjax']); ?>
        <div class="card-box">

            <div class="table-responsive">
                <?= GridView::widget([
        'dataProvider' => $dataProvider1,
        'summary' => '<h4>Контакты</h4>',
        //'filterModel' => $searchModel1,
        'emptyText' => Yii::t('app', 'There is no one contact'),
                       'tableOptions' => [ 'id' => 'users',
        'class' => 'table table-hover mails m-0 table table-actions-bar', ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

             'client_name',
           // 'addressname:ntext',

            'phone',
            'email:email',
            'birthday:date',
            'type',
           // [
           // 'label' => 'Организация',
           // 'value' => 'organization.mainaddress_adressname',
           // ],

        ],
    ]); ?>

            </div></div>
        <button class="btn btn-info" data-toggle="collapse" data-target="#hide-me"><?=Yii::t('app', 'Add contact')?></button>
        <div id="hide-me" class="collapse"><br>
            <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]); ?>

            <?= $form->field($contacts, 'client_name') ?>
            <?= $form->field($contacts, 'addressname') ?>
            <?= $form->field($contacts, 'phone') ?>
            <?= $form->field($contacts, 'email') ?>
            <?= $form->field($contacts, 'type') ?>
            <?php echo $form->field($contacts, 'birthday')->widget(\kartik\date\DatePicker::classname(), [
                'type' => \kartik\date\DatePicker::TYPE_COMPONENT_APPEND,
                'pickerButton' => false,
                'language' => 'ru',
                'options' => [
                    'placeholder' => Yii::t('app', 'Select date')
                ],
                'pluginOptions' => [
                    'autoclose' => true,
                    'showMeridian' => true,
                    'format' => 'yyyy-mm-dd',
                    'minView' => 2,
                ]
            ]) ?>
            <?= Html::submitButton(Yii::t('app', 'Save contact'), ['class' => 'btn btn-primary']) ?>
            <br><br>

            <?php ActiveForm::end(); ?>
        </div><br> <br><?=Alert::widget()?><br>
        <div class="card-box">

            <div class="table-responsive">

         <?= GridView::widget([
        'dataProvider' => $dataProvider,
       'summary' => '<h4 style="text-align: center; margin: 0px;">Заметки</h4>',
           //  'filterModel' => $searchModel,
                'emptyText' => Yii::t('app', 'There is no notes'),
                 'tableOptions' => [
        'class' => 'table table-hover mails m-0 table table-actions-bar', ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
			//'organization_id',

                [ 'attribute' => 'note',
              'format' => 'ntext' ],
           [ 'label' => 'Автор',
                'attribute' => 'user.username',
  ],

                'createdAt',
          ['class' => 'yii\grid\ActionColumn',
            'header' => 'Действия',
            'template' => '{delete}',
             'urlCreator' => function ($action, $model1, $key, $index) {
            if ($action === 'update') {
                return Url::to(['organization-notes/update', 'id' => $model1->id]);
              }
                else {
                return Url::to(['organization-notes/delete', 'id' => $model1->id]);
                }}


                ],
        ],
    ]); ?>
            </div>
        </div>
    <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]); ?>
    <?= $form->field($model1, 'note')->label(Yii::t('app', 'New note')) ?>
    <?= Html::submitButton(Yii::t('app', 'Add note'), ['class' => 'btn btn-primary']) ?>
        <br><br>

    <?php ActiveForm::end(); ?>
    <?php Pjax::end(); ?>

    </div>
</div>